# Generated by Django 3.1.3 on 2020-11-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='coordinateX',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='city',
            name='coordinateY',
            field=models.FloatField(default=0.0),
        ),
    ]
